const $=id=>document.getElementById(id);
const sliders=['tree','pave','wind','tower','water'];
const defaults={tree:35,pave:20,wind:30,tower:1,water:10};
const heatBase=[30.4,31.2,32.1,33.0,29.8,31.8,33.8,34.6,29.4,30.7,32.8,35.0,28.9,30.1,31.7,33.4];

function toast(msg){const t=$('toast');t.textContent=msg;t.classList.add('show');clearTimeout(window._toast);window._toast=setTimeout(()=>t.classList.remove('show'),2800)}
function renderHeat(){const map=$('heatmap');map.innerHTML='';heatBase.forEach((v,i)=>{const cell=document.createElement('button');cell.className='heat-cell';cell.textContent=`${v.toFixed(1)}°`;cell.style.setProperty('--heat',`${Math.max(0,Math.min(1,(v-28)/8))}`);cell.setAttribute('aria-label',`A-${String(i+1).padStart(2,'0')} ${v.toFixed(1)}도`);cell.onclick=()=>selectZone(i,v);map.appendChild(cell)});selectZone(2,heatBase[2])}
function selectZone(i,v){$('zoneName').textContent=`A-${String(i+1).padStart(2,'0')}`;$('zoneTemp').textContent=`${v.toFixed(1)}°C`;$('zoneAdvice').textContent=v>33?'수목 그늘 + 바람길 확보 우선 권장':v>31?'쿨포장과 그늘을 함께 적용 권장':'현재 조건은 비교적 양호합니다.'}
function calc(){const t=+$('tree').value,p=+$('pave').value,w=+$('wind').value,tw=+$('tower').value,wa=+$('water').value;const drop=Math.min(5.2,0.014*t+0.012*p+0.017*w+0.28*tw+0.018*wa);const temp=31.2-drop;const comfort=Math.min(99,Math.round(66+drop*5.8));const vent=Math.round(Math.min(100,w*0.72+tw*9));const improvement=Math.round(Math.min(96,35+drop*11+vent*.18));$('treeOut').textContent=`${t}%`;$('paveOut').textContent=`${p}%`;$('windOut').textContent=`${w}%`;$('towerOut').textContent=`${tw}개`;$('waterOut').textContent=`${wa}%`;$('predTemp').textContent=`${temp.toFixed(1)}°C`;$('predDrop').textContent=`-${drop.toFixed(1)}°C`;$('predComfort').textContent=`${comfort} / 100`;$('gaugeFill').style.width=`${improvement}%`;$('gaugeText').textContent=`열쾌적 개선 ${improvement}%`;$('ventEffect').textContent=vent>70?'매우 높음':vent>45?'높음':'중간';$('uhiPotential').textContent=drop>3.2?'매우 높음':drop>2?'높음':'중간';$('recommendation').textContent=`수목 ${Math.min(60,Math.max(35,Math.round(t+10)))}% + 바람길 ${Math.min(80,Math.max(50,Math.round(w+25)))}% + 쿨포장 ${Math.min(50,Math.max(30,Math.round(p+15)))}%`;$('recommendationDetail').textContent=tw>=2?'환기 타워를 통풍축과 연결하면 자연환기 효과가 커집니다.':'그늘을 먼저 확보하고 주요 보행축을 바람길과 연결하는 것이 효율적입니다.';$('savingValue').textContent=`-${drop.toFixed(1)}°C`;localStorage.setItem('thermoflowScenario',JSON.stringify({t,p,w,tw,wa,drop,temp,comfort}))}
sliders.forEach(id=>$(id).addEventListener('input',calc));
$('resetBtn').onclick=()=>{sliders.forEach(id=>$(id).value=defaults[id]);calc();toast('기본 시나리오로 초기화했습니다.')};
$('optimizeBtn').onclick=()=>{let best=null;for(let t=25;t<=70;t+=5)for(let p=15;p<=55;p+=5)for(let w=35;w<=80;w+=5)for(let tw=0;tw<=4;tw++)for(let wa=0;wa<=30;wa+=10){const drop=Math.min(5.2,.014*t+.012*p+.017*w+.28*tw+.018*wa);const cost=t*.55+p*.3+w*.45+tw*18+wa*.35;const score=drop*20-cost*.018;if(!best||score>best.score)best={t,p,w,tw,wa,score}}$('tree').value=best.t;$('pave').value=best.p;$('wind').value=best.w;$('tower').value=best.tw;$('water').value=best.wa;calc();toast('AI가 저감효과와 설계변수의 균형을 고려해 최적안을 제안했습니다.')};
$('weatherBtn').onclick=async()=>{toast('기상 데이터를 불러오는 중입니다…');try{const lat=37.2636,lon=127.0286;const r=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${lat}&longitude=${lon}&current=temperature_2m,relative_humidity_2m,wind_speed_10m,weather_code&timezone=Asia%2FSeoul`);const d=await r.json();const temp=d.current.temperature_2m;$('tempValue').textContent=`${temp.toFixed(1)}°C`;$('weatherText').textContent=`수원 기준 · 습도 ${d.current.relative_humidity_2m}% · 풍속 ${d.current.wind_speed_10m} km/h`;const c=Math.max(20,Math.min(95,Math.round(88-(temp-24)*4)));$('comfortValue').textContent=c;$('comfortText').textContent=c<55?'위험 · 즉시 그늘·휴식 필요':c<75?'주의 · 그늘 필요':'양호 · 보행 가능';$('comfortText').className=c<55?'danger':c<75?'warn':'good';toast('실시간 기상 데이터를 반영했습니다.')}catch(e){toast('기상 데이터 연결에 실패해 예시값을 유지합니다.')}};
$('locationBtn').onclick=()=>{if(!navigator.geolocation){toast('브라우저 위치 기능을 사용할 수 없습니다.');return}navigator.geolocation.getCurrentPosition(pos=>{toast(`현재 위치의 위도 ${pos.coords.latitude.toFixed(3)}, 경도 ${pos.coords.longitude.toFixed(3)}를 분석 대상으로 설정했습니다.`)},()=>toast('위치 권한이 없어 기본 지역을 유지합니다.'))};
document.querySelectorAll('[data-action]').forEach(btn=>btn.onclick=()=>{const a=btn.dataset.action;if(a==='save'){localStorage.setItem('thermoflowSaved','true');toast('현재 시나리오를 이 브라우저에 저장했습니다.')}else if(a==='share'){navigator.clipboard?.writeText(location.href);toast('현재 플랫폼 주소를 클립보드에 복사했습니다.')}else{const s=JSON.parse(localStorage.getItem('thermoflowScenario')||'{}');toast(`분석 리포트: 예상 저감량 ${s.drop?s.drop.toFixed(1):'2.1'}°C · 열쾌적 ${s.comfort||81}/100`)}});
renderHeat();calc();
